### PR TITLE
added data-if directive - Listen for changes to an attribute and remove the element if the value is undefined or false, adding it otherwise

### PR DESCRIPTION
**Pull request by litenull**
Listen for changes to an attribute and remove the element if the value is undefined or false, adding it otherwise

### CODE REVIEW

**Comment by braddunbar** [comment]
Hi @litenull!  Have you tried `data-show` and `data-hide` already?  It's generally easier than adding or removing the element from the page.

**Comment by litenull** [comment]
Yeah, but this is a different case.  

When doing big apps, this is very useful, since show/hide only shows/hides elements. But the DOM is still full of non-used elements. Also, very useful when showing/removing data that isnt supposed to be there when the condition is given.

**Comment by braddunbar** [comment]
In my experience, leaving some unused, hidden DOM elements around doesn't cause any noticeable performance problems and is much simpler.  I'd recommend going that route.  :)

**Comment by litenull** [comment]
Ah, ok. Nevermind then. Awesome plugin, btw.

**Comment by braddunbar** [comment]
Thank you!  :smile:

**Pull request closed without merging**
